### ISSUE TITLE
Dependency on Powershell

### ISSUE THREAD

**Issue by riponbanik** [voxpupuli/puppet-iis#160] opened 2016-11-02 00:56 UTC
librain-puppet dependency issue when using new version of puppetlabs/powershell, can you please modify the metadata.json so that it does not depend on old version of powershell anymore?

**Comment by alexjfisher** [comment] 2016-11-02 17:38
Duplicate of https://github.com/voxpupuli/puppet-iis/issues/131

**Comment by alexjfisher** [comment] 2016-11-02 17:40
@riponbanik Have you tried puppet/iis with puppetlabs/powershell 2.x.  Did it work?

**Comment by riponbanik** [comment] 2016-11-03 20:35
It worked. But librarian-puppet fail to install modules if there is any dependency issue where one module requires powershell > 2 and this module requires powershell < 2

**Comment by alexjfisher** [comment] 2016-11-03 22:11
@riponbanik Thanks for testing.  We should be able to adjust the metadata to fix this issue.  We have another windows module with the same dependency issue, but it turned out that module *didn't* work correctly with puppetlabs/powershell 2 without fixes.

**Comment by rdev5** [comment] 2016-11-07 16:54
Possibly related: https://github.com/puppetlabs/puppetlabs-powershell/pull/156

**Comment by bastelfreak** [comment] 2019-05-11 14:54
Hi. I'm going to close this Issue. We deprecated the module and the new version is available here: https://forge.puppet.com/puppetlabs/iis

**Closed by bastelfreak** 2019-05-11 14:54 UTC
