### ISSUE TITLE
Binding host header changes don't get picked up

### ISSUE THREAD

**Issue by ashic** [voxpupuli/puppet-iis#49] opened 2015-03-25 14:22 UTC
It seems:

``` puppet
iis::manage_site {'mysite':
      site_path     => 'C:\inetpub\wwwroot\mysite',
      port          => '80',
      #ssl           => 'false',
      ip_address    => '*',
      host_header   => 'qa-mysite.mydomain.com',
      app_pool      => 'myapppool',
    }
```

Creates the site with the correct binding, but if we change the host header, it doesn't register as a change. In other words, if I change host_header to "foo-bar.somesite.com", puppet runs, sees there's no changes and carries on.

**Comment by roberteckdale** [comment] 2016-03-02 18:03
I can confirm this behavior. It also happens when updating the path of a virtual directory.

**Comment by rdev5** [comment] 2016-10-20 21:33
This is still a problem in 2016. Little concerning that we still have open issues with this module since 2015.

In the mean time, you can just add an `exec` to your manifest:

```
exec {'Update bindings':
  command => 'Import-Module WebAdministration; Set-WebBinding -Name "www.example.com" -HostHeader "original.example.com" -PropertyName "HostHeader" -Value "new.example.com"',
  provider = 'powershell'
}
```

**Comment by bastelfreak** [comment] 2019-05-11 14:57
Hi. I'm going to close this Issue. We deprecated the module and the new version is available here: https://forge.puppet.com/puppetlabs/iis

**Closed by bastelfreak** 2019-05-11 14:57 UTC
