### ISSUE TITLE
Constant Execution of exec

### ISSUE THREAD

**Issue by jwtdrjj** [voxpupuli/puppet-iis#153] opened 2016-09-07 20:27 UTC
### Affected Puppet, Ruby, OS and module versions/distributions
- Puppet:  2016.4.2
- Ruby: 
- Distribution:
- Module version: v2.0.2
### How to reproduce (e.g Puppet code you use)

``` puppet
      iis::manage_binding { "${sitename}_all_HTTPS":
        site_name              => $sitename,
        protocol               => 'https',
        port                   => '443',
        ip_address             => '*',
        certificate_thumbprint => hiera("cert::www-${tier}_bna_com::thumbprint"),
        require                => [
          Iis::Manage_site[$sitename],
          Cert_pfxcertificate::Import["www ${tier} server cert"]],
      }
```
### What are you seeing

``` puppet
exec { "Attach-Certificate-${title}":
  command   => "C:\\temp\\create-${name}.ps1",
  onlyif    => "C:\\temp\\inspect-${name}.ps1",
  require   => [File["inspect-${title}-certificate.ps1"], File["create-${title}-certificate.ps1"]],
  provider  => powershell,
  logoutput => true,
}
```
### What behaviour did you expect instead

I would expect it to only execute once.

**Comment by ffrank** [comment] 2016-09-14 14:14
Hi,

could you share the content of `C:\temp\inspect-*.ps1` as generated on your agent system?

**Comment by jwtdrjj** [comment] 2016-09-22 17:40
Here you go.  Thanks, 

[inspect-BnaCart-q - remove prod HTTPS binding.txt](https://github.com/voxpupuli/puppet-iis/files/487991/inspect-BnaCart-q.-.remove.prod.HTTPS.binding.txt)

**Comment by jwtdrjj** [comment] 2016-09-22 17:42
here you go

**Comment by jwtdrjj** [comment] 2016-09-22 17:43
[inspect-BnaCartHTTPS.txt](https://github.com/voxpupuli/puppet-iis/files/488011/inspect-BnaCartHTTPS.txt)
[inspect-BnaCartremoveHTTPS.txt](https://github.com/voxpupuli/puppet-iis/files/488012/inspect-BnaCartremoveHTTPS.txt)

**Comment by jwtdrjj** [comment] 2016-09-22 17:43
There you go, 

Thanks, 

Jacob

**Comment by ffrank** [comment] 2016-09-22 23:38
Cool, thanks. So there are two HTTPS bindings managed on this machine?

The `inspect-BnaCartremoveHTTPS.txt` looks weird, as though it was generated from the `create-` template rather than the `inspect-` one.

I'll have to look into the issue more closely...

**Comment by ffrank** [comment] 2016-09-26 00:12
More questions: Are *all* these HTTPS bindings firing on every run?

Also, could this be a duplicate of #33? Spaces in binding names seem to be an issue...?

**Comment by jwtdrjj** [comment] 2016-09-26 13:18
yes they are firing on everyone and I do have a c;\temp directory so I don't think that is the issue.

**Comment by jwtdrjj** [comment] 2016-09-26 13:19
2016-09-26
13:17 Z
notice	
Local environment: 'production' doesn't match server specified node environment 'development', switching agent to 'development'.
Source:	Puppet
2016-09-26
13:18 Z
notice	
Source:	/Stage[main]/Bna_iis::Bna::Cart/Iis::Manage_binding[BnaCart-a - all HTTPS]/Exec[Attach-Certificate-BnaCart-a - all HTTPS]/returnsFile:	/etc/puppetlabs/code/environments/development/modules/iis/manifests/manage_binding.ppLine:	48
2016-09-26
13:18 Z
notice	
+ CategoryInfo : ObjectNotFound: (C:\temp\create-BnaCart-a:String) [], CommandNotFoundException
Source:	/Stage[main]/Bna_iis::Bna::Cart/Iis::Manage_binding[BnaCart-a - all HTTPS]/Exec[Attach-Certificate-BnaCart-a - all HTTPS]/returnsFile:	/etc/puppetlabs/code/environments/development/modules/iis/manifests/manage_binding.ppLine:	48
2016-09-26
13:18 Z
notice	
+ FullyQualifiedErrorId : CommandNotFoundException
Source:	/Stage[main]/Bna_iis::Bna::Cart/Iis::Manage_binding[BnaCart-a - all HTTPS]/Exec[Attach-Certificate-BnaCart-a - all HTTPS]/returnsFile:	/etc/puppetlabs/code/environments/development/modules/iis/manifests/manage_binding.ppLine:	48
2016-09-26
13:18 Z
notice	
+ C:\temp\create-BnaCart-a - all HTTPS.ps1
Source:	/Stage[main]/Bna_iis::Bna::Cart/Iis::Manage_binding[BnaCart-a - all HTTPS]/Exec[Attach-Certificate-BnaCart-a - all HTTPS]/returnsFile:	/etc/puppetlabs/code/environments/development/modules/iis/manifests/manage_binding.ppLine:	48
2016-09-26
13:18 Z
notice	
+ ~~~~~~~~~~~~~~~~~~~~~~~~
Source:	/Stage[main]/Bna_iis::Bna::Cart/Iis::Manage_binding[BnaCart-a - all HTTPS]/Exec[Attach-Certificate-BnaCart-a - all HTTPS]/returnsFile:	/etc/puppetlabs/code/environments/development/modules/iis/manifests/manage_binding.ppLine:	48
2016-09-26
13:18 Z
notice	
At line:1 char:1
Source:	/Stage[main]/Bna_iis::Bna::Cart/Iis::Manage_binding[BnaCart-a - all HTTPS]/Exec[Attach-Certificate-BnaCart-a - all HTTPS]/returnsFile:	/etc/puppetlabs/code/environments/development/modules/iis/manifests/manage_binding.ppLine:	48
2016-09-26
13:18 Z
notice	
C:\temp\create-BnaCart-a : The term 'C:\temp\create-BnaCart-a' is not recognized as the name of a cmdlet, function, 
Source:	/Stage[main]/Bna_iis::Bna::Cart/Iis::Manage_binding[BnaCart-a - all HTTPS]/Exec[Attach-Certificate-BnaCart-a - all HTTPS]/returnsFile:	/etc/puppetlabs/code/environments/development/modules/iis/manifests/manage_binding.ppLine:	48
2016-09-26
13:18 Z
notice	
correct and try again.
Source:	/Stage[main]/Bna_iis::Bna::Cart/Iis::Manage_binding[BnaCart-a - all HTTPS]/Exec[Attach-Certificate-BnaCart-a - all HTTPS]/returnsFile:	/etc/puppetlabs/code/environments/development/modules/iis/manifests/manage_binding.ppLine:	48
2016-09-26
13:18 Z
notice	
executed successfully
Source:	/Stage[main]/Bna_iis::Bna::Cart/Iis::Manage_binding[BnaCart-a - all HTTPS]/Exec[Attach-Certificate-BnaCart-a - all HTTPS]/returnsFile:	/etc/puppetlabs/code/environments/development/modules/iis/manifests/manage_binding.ppLine:	48
2016-09-26
13:18 Z
notice	
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is 
Source:	/Stage[main]/Bna_iis::Bna::Cart/Iis::Manage_binding[BnaCart-a - all HTTPS]/Exec[Attach-Certificate-BnaCart-a - all HTTPS]/returnsFile:	/etc/puppetlabs/code/environments/development/modules/iis/manifests/manage_binding.ppLine:	48
2016-09-26
13:18 Z
notice	
Applied catalog in 32.55 s

**Comment by ffrank** [comment] 2016-09-26 20:56
Ah, well, I was actually thinking of [this comment](https://github.com/voxpupuli/puppet-iis/issues/33#issuecomment-168236187). Could you try changing your resource title so that they don't contain spaces anymore.

E.g. `manage_binding { 'BnaCart-a_-_all_HTTPS': ... }` with underscores instead of spaces.

If this does the trick, I will address this by adding code to make sure spaces are no longer accepted in the first place. (Or, fix the script, but that sounds boring ;-)

**Comment by jwtdrjj** [comment] 2016-09-27 13:24
I will try that and let you know

**Comment by jwtdrjj** [comment] 2016-09-29 13:07
I refactored the names and pushed to my dev, but no change.

2016-09-29
13:05 Z
notice	
Local environment: 'production' doesn't match server specified node environment 'development', switching agent to 'development'.
Source:	Puppet
2016-09-29
13:06 Z
notice	
Source:	/Stage[main]/Bna_iis::Ecds::Messagebus/Iis::Manage_binding[backoffice-alp.services.bna.com_-_net.msmq]/Exec[CreateBinding-backoffice-alp.services.bna.com_-_net.msmq]/returnsFile:	/etc/puppetlabs/code/environments/development/modules/iis/manifests/manage_binding.ppLine:	22
2016-09-29
13:06 Z
notice	
+ CategoryInfo : InvalidArgument: (:) [New-WebBinding], ParameterBindingException
Source:	/Stage[main]/Bna_iis::Ecds::Messagebus/Iis::Manage_binding[backoffice-alp.services.bna.com_-_net.msmq]/Exec[CreateBinding-backoffice-alp.services.bna.com_-_net.msmq]/returnsFile:	/etc/puppetlabs/code/environments/development/modules/iis/manifests/manage_binding.ppLine:	22
2016-09-29
13:06 Z
notice	
+ FullyQualifiedErrorId : MissingArgument,Microsoft.IIs.PowerShell.Provider.NewWebBindingCommand
Source:	/Stage[main]/Bna_iis::Ecds::Messagebus/Iis::Manage_binding[backoffice-alp.services.bna.com_-_net.msmq]/Exec[CreateBinding-backoffice-alp.services.bna.com_-_net.msmq]/returnsFile:	/etc/puppetlabs/code/environments/development/modules/iis/manifests/manage_binding.ppLine:	22
2016-09-29
13:06 Z
notice	
+ ~~~~~
Source:	/Stage[main]/Bna_iis::Ecds::Messagebus/Iis::Manage_binding[backoffice-alp.services.bna.com_-_net.msmq]/Exec[CreateBinding-backoffice-alp.services.bna.com_-_net.msmq]/returnsFile:	/etc/puppetlabs/code/environments/development/modules/iis/manifests/manage_binding.ppLine:	22
2016-09-29
13:06 Z
notice	
+ ... vices.bna.com" -Port -Protocol "netmsmq" -HostHeader "" -IPAddress "*" -SslFlag ...
Source:	/Stage[main]/Bna_iis::Ecds::Messagebus/Iis::Manage_binding[backoffice-alp.services.bna.com_-_net.msmq]/Exec[CreateBinding-backoffice-alp.services.bna.com_-_net.msmq]/returnsFile:	/etc/puppetlabs/code/environments/development/modules/iis/manifests/manage_binding.ppLine:	22
2016-09-29
13:06 Z
notice	
At line:1 char:89
Source:	/Stage[main]/Bna_iis::Ecds::Messagebus/Iis::Manage_binding[backoffice-alp.services.bna.com_-_net.msmq]/Exec[CreateBinding-backoffice-alp.services.bna.com_-_net.msmq]/returnsFile:	/etc/puppetlabs/code/environments/development/modules/iis/manifests/manage_binding.ppLine:	22
2016-09-29
13:06 Z
notice	
New-WebBinding : Missing an argument for parameter 'Port'. Specify a parameter of type 'System.UInt32' and try again.
Source:	/Stage[main]/Bna_iis::Ecds::Messagebus/Iis::Manage_binding[backoffice-alp.services.bna.com_-_net.msmq]/Exec[CreateBinding-backoffice-alp.services.bna.com_-_net.msmq]/returnsFile:	/etc/puppetlabs/code/environments/development/modules/iis/manifests/manage_binding.ppLine:	22
2016-09-29
13:06 Z
notice	
executed successfully
Source:	/Stage[main]/Bna_iis::Ecds::Messagebus/Iis::Manage_binding[backoffice-alp.services.bna.com_-_net.msmq]/Exec[CreateBinding-backoffice-alp.services.bna.com_-_net.msmq]/returnsFile:	/etc/puppetlabs/code/environments/development/modules/iis/manifests/manage_binding.ppLine:	22
2016-09-29
13:06 Z
notice	
Applied catalog in

**Comment by jwtdrjj** [comment] 2016-09-29 13:09
on another one I get this.

2016-09-29
12:42 Z
notice	
Local environment: 'production' doesn't match server specified node environment 'development', switching agent to 'development'.
Source:	Puppet
2016-09-29
12:43 Z
notice	
executed successfully
Source:	/Stage[main]/Bna_iis::Bna::Cart/Iis::Manage_binding[BnaCart-d_-_all_HTTPS]/Exec[Attach-Certificate-BnaCart-d_-_all_HTTPS]/returnsFile:	/etc/puppetlabs/code/environments/development/modules/iis/manifests/manage_binding.ppLine:	48
2016-09-29
12:43 Z
notice	
Applied catalog in 41.00 seconds

Should it still be executing?

**Comment by ffrank** [comment] 2016-09-29 14:37
Humm, bummer. I cannot reproduce for lack of a Windows box. So I'm afraid I won't be able to dig into this any further.

**Comment by jwtdrjj** [comment] 2016-09-29 15:37
alright, thanks

**Comment by jwtdrjj** [comment] 2016-09-30 13:31
one last thing.

I think removing the spaces helped but now its still constantly executing.

executed successfully
Source:	/Stage[main]/Bna_iis::Bna::Cart/Iis::Manage_binding[BnaCart-q_-_all_HTTPS]/Exec[Attach-Certificate-BnaCart-q_-_all_HTTPS]/returnsFile:	/etc/puppetlabs/code/environments/testing/modules/iis/manifests/manage_binding.ppLine:	48

not sure why?

**Comment by jwtdrjj** [comment] 2016-09-30 13:47
I also I have noticed that this.
Test-Path IIS:\SslBindings\*!443,IIS:\SslBindings\*!443!

returns
true
false

so none of the inspection is actually done.

**Comment by ffrank** [comment] 2016-09-30 14:06
Could you please edit your comments and add some formatting? It's hard to see what's going on, particularly the "returns true false" part. Thanks!

**Comment by jwtdrjj** [comment] 2016-09-30 14:28
In the inspect-xxxx.ps1 is an if statement.
if((Test-Path IIS:\SslBindings\*!443,IIS:\SslBindings\*!443!) -eq $true)

This if statement returns two values, true and false
Test-Path IIS:\SslBindings\*!443 returns true
Test-Path IIS:\SslBindings\*!443! returns false

The if statement is not satisfied so the code is skipped and not test is done.

**Comment by ffrank** [comment] 2016-09-30 21:14
Oh, OK, now I got you. Thanks again.

Good catch, this might be an issue indeed. So in Windows, does `exit 0` mean that the test failed?

This could be a bug, because the second query is expanded from

```erb
IIS:\SslBindings\<%= @ip_address %>!<%= @port %>!<%= @host_header %>
```

Perhaps this makes no sense if `$host_header` is empty?

I looked at the history, and this second query was introduced in the squash commit 762b8. I cannot easily tell the reasoning. I guess this is about SNI?

Could you try passing a sensible `host_header` parameter value? See if that helps?

**Comment by jwtdrjj** [comment] 2016-12-07 14:19
I think the inspect-certificate-bindings.ps1.erb should be like this.

```
Import-Module WebAdministration
if((Test-Path IIS:\SslBindings\<%= @ip_address %>!<%= @port %>) -or (Test-Path IIS:\SslBindings\<%= @ip_address %>!<%= @port %>!<%= @host_header %>)) {
    $site = Get-Website | Where-Object { $_.Name -eq "<%= @site_name %>" }
    $store = "<%= @store %>"
    $certsAttachedToSite = Get-ChildItem IIS:\SSLBindings | ? { $site | Select-Object { $_ -contains $_.Sites.Value }} | % { $_.Thumbprint }
    $certificate = Get-ChildItem CERT:\LocalMachine\$store | ? { $certsAttachedToSite -contains $_.Thumbprint} | Where-Object { $_.Thumbprint -eq "<%= @certificate_thumbprint %>" }
    if ($certificate -ne $null ){
        exit 1
    }
    else {
        exit 0
    }
}
else {
    exit 0
}
```

**Comment by ffrank** [comment] 2016-12-12 14:38
Cool. Way to go @jwtdrjj thanks for the patch. Is this resolved then?

**Comment by jwtdrjj** [comment] 2016-12-13 18:52
well I now get the correct exit code but its still consistently notifying.  I am starting to debug again.

**Comment by jwtdrjj** [comment] 2016-12-13 20:15
ok new wrinkle

`exec { "Attach-Certificate-${title}":
        command   => "C:\\temp\\create-${name}.ps1",
        onlyif    => "C:\\temp\\insert-${name}.ps1",
        require   => [File["inspect-${title}-certificate.ps1"], File["create-${title}-certificate.ps1"]],
        provider  => powershell,
        logoutput => true,`

This code returns an exit code of 1 and thats what we want but it still executes.

`exec { "Attach-Certificate-${title}":
        command   => "C:\\temp\\create-${name}.ps1",
        onlyif    => "Import-Module WebAdministration;
                      if((Test-Path IIS:\\SslBindings\\\'${ip_address}\'!\'${port}\') -Or (Test-Path IIS:\\SslBindings\\\'${ip_address}\'!\'${port}\'!$\'{host_header}\'));
                      {;
                        $site = Get-Website | Where-Object { $_.Name -eq \'${site_name}\' };
                        $store = \'${store}\';
                        $certsAttachedToSite = Get-ChildItem IIS:\\SSLBindings | ? { $site | Select-Object { $_ -contains $_.Sites.Value }} | % { $_.Thumbprint };
                        $certificate = Get-ChildItem CERT:\\LocalMachine\\$store | ? { $certsAttachedToSite -contains $_.Thumbprint} | Where-Object { $_.Thumbprint -eq \'${$certificate_thumbprint}\' };
	                      if ($certificate -ne $null ){exit 1};
                        else {exit 0};};
                      else {exit 0}",
        require   => [File["inspect-${title}-certificate.ps1"], File["create-${title}-certificate.ps1"]],
        provider  => powershell,
        logoutput => true,`

I take the code out of the erb and put it straight in the onlyif parameter and it no longer executes every run.

Does anyone have any thoughts?

**Comment by ffrank** [comment] 2016-12-16 09:31
I daresay it does not execute **at all** anymore. A piece of Powershell code is not a valid command, so it just silently fails and hence breaks the `onlyif` condition.

**Comment by bastelfreak** [comment] 2019-05-11 14:54
Hi. I'm going to close this Issue. We deprecated the module and the new version is available here: https://forge.puppet.com/puppetlabs/iis

**Closed by bastelfreak** 2019-05-11 14:54 UTC
