### ISSUE TITLE
idleTimeoutAction

### ISSUE THREAD

**Issue by stephenbawks** [voxpupuli/puppet-iis#112] opened 2016-05-11 18:22 UTC
Was adding some code to the manage_app_pool.pp file and I was just looking to see if someone might be able to double check my work here.  Working on a Windows box and I don't have the tools available to do a lot of the unit testing.

commit number:  397bff6138e442e349352bf2d9fe5f4b372cd893

Adding a new value to control the idleActionTimeout so that we can change it to Suspend or Terminate.

``` puppet
$apppool_idle_Timeout_action      = 'Terminate'

validate_re($apppool_idle_Timeout_action, '^(Suspend|Terminate)$')

exec { "IdleTimeoutAction-${app_pool_name}":
  command   => "Import-Module WebAdministration; Set-ItemProperty \"IIS:\\AppPools\\${app_pool_name}\" startMode ${apppool_idle_Timeout_action}",
  provider  => powershell,
  onlyif    => "Import-Module WebAdministration; if((Get-ItemProperty \"IIS:\\AppPools\\${app_pool_name}\" startMode).CompareTo('${apppool_idle_Timeout_action}') -eq 0) { exit 1 } else { exit 0 }",
  require   => Exec["Create-${app_pool_name}"],
  logoutput => true,
}
```

**Comment by petems** [comment] 2016-05-27 10:00
@gigadafud Looks ok, I would gate the logic behind the new parameter however:

```
$apppool_idle_Timeout_action      = 'Terminate'

if $apppool_idle_Timeout_action {
validate_re($apppool_idle_Timeout_action, '^(Suspend|Terminate)$')

exec { "IdleTimeoutAction-${app_pool_name}":
  command   => "Import-Module WebAdministration; Set-ItemProperty \"IIS:\\AppPools\\${app_pool_name}\" startMode ${apppool_idle_Timeout_action}",
  provider  => powershell,
  onlyif    => "Import-Module WebAdministration; if((Get-ItemProperty \"IIS:\\AppPools\\${app_pool_name}\" startMode).CompareTo('${apppool_idle_Timeout_action}') -eq 0) { exit 1 } else { exit 0 }",
  require   => Exec["Create-${app_pool_name}"],
  logoutput => true,
}

}
```

Feel free to PR! 👍

**Comment by gigadafud** [comment] 2016-05-27 11:23
Thank you sir.  I have gone ahead and done what you have suggested.  Pull request has been submitted.

**Comment by gigadafud** [comment] 2016-06-09 19:49
So it looks what I have above is wrong.  Looks like I had a copy/paste issue.  I have startmode in there which is going to mess with the startmode action above.  I have corrected it with this, so I need to issue another pull request.

    if $apppool_idle_timeout_action {
      validate_re($apppool_idle_timeout_action, '^(Suspend|Terminate)$')
      exec { "IdleTimeoutAction-${app_pool_name}":
        command   => "Import-Module WebAdministration; Set-ItemProperty \"IIS:\\AppPools\\${app_pool_name}\" processmodel.idletimeoutaction ${apppool_idle_timeout_action}",
        provider  => powershell,
        onlyif    => "Import-Module WebAdministration; if((Get-ItemProperty \"IIS:\\AppPools\\${app_pool_name}\" processmodel.idletimeoutaction).CompareTo('${apppool_idle_timeout_action}') -eq 0) { exit 1 } else { exit 0 }",
        require   => Exec["Create-${app_pool_name}"],
        logoutput => true,
      }
    }

**Comment by gigadafud** [comment] 2016-06-12 15:32
Actually one more update.  I had all lower casing for the the process model idleactiontimeout and it NEEDS to be processmodel.idleTimeoutAction because casing matters on that one. What I have below should be correct now.  Seeing expected behavior now.  I will update the pull request.


    if $apppool_idle_timeout_action != undef {
      validate_re($apppool_idle_timeout_action, '^(Suspend|Terminate)$')
      exec { "IdleTimeoutAction-${app_pool_name}":
        command   => "Import-Module WebAdministration; Set-ItemProperty \"IIS:\\AppPools\\${app_pool_name}\" processmodel.idleTimeoutAction ${apppool_idle_timeout_action}",
        provider  => powershell,
        onlyif    => "Import-Module WebAdministration; if((Get-ItemProperty \"IIS:\\AppPools\\${app_pool_name}\" processmodel.idleTimeoutAction).CompareTo('${apppool_idle_timeout_action}') -eq 0) { exit 1 } else { exit 0 }",
        require   => Exec["Create-${app_pool_name}"],
        logoutput => true,
      }
    }

**Comment by bastelfreak** [comment] 2019-05-11 14:57
Hi. I'm going to close this Issue. We deprecated the module and the new version is available here: https://forge.puppet.com/puppetlabs/iis

**Closed by bastelfreak** 2019-05-11 14:57 UTC
Labels: needs-feedback, question
