### ISSUE TITLE
Add an application under an IIS website

### ISSUE THREAD

**Issue by S-Sudarsan** [voxpupuli/puppet-iis#50] opened 2015-03-26 18:07 UTC
Hi,

I am setting up a website in IIS with the below snippet

iis::manage_site {'Demo':
    site_path     => 'C:\inetpub\wwwroot\Demo',
    port          => '80',
    ip_address    => '*',
    app_pool      => 'Demo',
  }

However I have few folders under "Demo" which needs to be converted to an application and not to be used as a virtual directory. Is there an equivalent of "iis::manage_virtual_application" for setting up an application.

**Comment by ferventcoder** [comment] 2015-03-26 21:26
Guessing this is the same as http://stackoverflow.com/questions/29285955/how-to-create-an-application-under-a-website-using-puppet

**Comment by S-Sudarsan** [comment] 2015-03-27 09:42
Yes, it is the same. Thanks

**Comment by ferventcoder** [comment] 2015-03-27 19:29
@liamjbennett @amwilson I believe this can be closed as duplicate of #43

**Closed** 2016-06-10 11:01 UTC
